### Importing Libraries

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Importing Dataset

In [25]:
df=pd.read_csv(r"C:\Users\SK\Downloads\housing_price_dataset.csv")
df

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0            2126         4          1        Rural       1969  215355.283618
1            2459         3          2        Rural       1980  195014.221626
2            1860         2          1       Suburb       1970  306891.012076
3            2294         2          1        Urban       1996  206786.787153
4            2130         5          2       Suburb       2001  272436.239065
...           ...       ...        ...          ...        ...            ...
49995        1282         5          3        Rural       1975  100080.865895
49996        2854         2          2       Suburb       1988  374507.656727
49997        2979         5          3       Suburb       1962  384110.555590
49998        2596         5          2        Rural       1984  380512.685957
49999        1572         5          3        Rural       2011  221618.583218

[50000 rows x 6 columns]

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   SquareFeet    50000 non-null  int64  
 1   Bedrooms      50000 non-null  int64  
 2   Bathrooms     50000 non-null  int64  
 3   Neighborhood  50000 non-null  object 
 4   YearBuilt     50000 non-null  int64  
 5   Price         50000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 2.3+ MB


#### Data Preproccesing

### EDA

In [27]:
df.isna().sum()

SquareFeet      0
Bedrooms        0
Bathrooms       0
Neighborhood    0
YearBuilt       0
Price           0
dtype: int64

In [28]:
df.duplicated().sum()

0

In [29]:
df.head()

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0        2126         4          1        Rural       1969  215355.283618
1        2459         3          2        Rural       1980  195014.221626
2        1860         2          1       Suburb       1970  306891.012076
3        2294         2          1        Urban       1996  206786.787153
4        2130         5          2       Suburb       2001  272436.239065

In [30]:
df['Neighborhood']=df['Neighborhood'].map({"Rural":1,"Suburb":2,"Urban":3})

In [31]:
df.head()

SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt          Price
0        2126         4          1             1       1969  215355.283618
1        2459         3          2             1       1980  195014.221626
2        1860         2          1             2       1970  306891.012076
3        2294         2          1             3       1996  206786.787153
4        2130         5          2             2       2001  272436.239065

### Model Building

#### Splitting into input and output

In [42]:
df.isna().sum()

SquareFeet      0
Bedrooms        0
Bathrooms       0
Neighborhood    0
YearBuilt       0
Price           0
dtype: int64

In [43]:
A=df['YearBuilt']

In [44]:
X=df.drop("Price",axis=1)
y=df['Price']

In [45]:
#pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


#### Splitting into Train and Test

In [33]:
from sklearn.model_selection import train_test_split

In [46]:
train_test_split(X,y,test_size=0.2,random_state=43)

[       SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt
 30415        2931         3          1             3       1988
 21710        2848         3          2             2       1989
 13743        2379         2          2             1       1971
 10137        1614         3          3             3       1955
 14471        1995         5          3             1       1952
 ...           ...       ...        ...           ...        ...
 25233        1233         4          3             2       2020
 18448        2080         3          1             1       1967
 40753        2293         2          1             3       1958
 19776        1854         3          1             2       1967
 14148        2240         5          3             1       2008
 
 [40000 rows x 5 columns],
        SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt
 7396         1548         3          2             2       1992
 29820        1933         2          2             3       1

In [47]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=23)

In [48]:
X_train.shape

(40000, 5)

In [49]:
y_train.shape

(40000,)

In [50]:
X_test.shape

(10000, 5)

In [51]:
y_test.shape

(10000,)

### KNN,Linear Regression,SVM,DT

#### KNN

In [52]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error,r2_score

In [53]:
knn=KNeighborsRegressor()
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,y_pred)))

54247.93901533543


### Linear Regression

In [56]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,y_pred)))

49403.976927995944


### Support Vector Regression

In [ ]:
from sklearn.svm import SVR
sv=SVR()
sv.fit(X_train,y_train)
y_pred=sv.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,y_pred)))

### Decision Tree

In [57]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor()
dt.fit(X_train,y_train)
y_pred=dt.predict(X_test)
print(np.sqrt(mean_squared_error(y_test,y_pred)))

72470.7609220074


In [58]:
lr.predict([[2250,5,2,3,2002]])[[0]]

C:\Users\SK\anaconda3\innomatics\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([257199.22508665])

In [59]:
lr.coef_

array([  99.31308607, 5168.85659283, 2625.12603247,  752.26187692,
        -13.64933459])

In [60]:
lr.intercept_

27719.428600464948

y=m1*x2+m2*x2.......+intercept

In [61]:
sqft=2250
bed=5
bath=2
nb=3
year=2002
price=99.31308607*sqft+5168.85659283*bed+2625.12603247*bath+752.26187692*nb-13.64933459*year+27719.428600464948

In [62]:
price

257199.22506863496

### Pickling

In [63]:
import pickle

In [65]:
pickle.dump(lr,open('lr.pkl','wb'))   #writing as a binary format file

In [66]:
model=pickle.load(open('lr.pkl','rb'))

In [67]:
model.predict([[2126,4,1,1,1969]])

C:\Users\SK\anaconda3\innomatics\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([236036.32407558])